# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_element', models.CharField(max_length=100)),
                ('uraian_element', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.CharField(blank=True, max_length=300)),
                ('satuan_element', models.CharField(blank=True, max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
