# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='kode_element',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
