# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0003_auto_20160121_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
