# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0005_auto_20160121_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='jenis_element',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
