# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0006_element_jenis_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jenis_element', models.CharField(max_length=8, unique=True)),
                ('nama_jenis_element', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='jenis_element',
        ),
    ]
