# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0007_auto_20160130_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='nama_jenis_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='element.JenisElement'),
            preserve_default=False,
        ),
    ]
