# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0008_element_nama_jenis_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='nama_jenis_element',
            new_name='jenis_element',
        ),
        migrations.RemoveField(
            model_name='jeniselement',
            name='nama_jenis_element',
        ),
        migrations.AddField(
            model_name='jeniselement',
            name='jenis_element',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
