# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0012_auto_20160130_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='harga_satuan',
            field=models.FloatField(),
        ),
    ]
