# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_rap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rap',
            options={'verbose_name': 'rap', 'verbose_name_plural': 'rap'},
        ),
    ]
