# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_ahs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahs',
            options={'verbose_name': 'ahs', 'verbose_name_plural': 'ahs'},
        ),
    ]
