# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_ahs', '0007_auto_20160204_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahs',
            name='nomor_ahs',
            field=models.CharField(max_length=7),
        ),
    ]
