# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0012_auto_20160130_0807'),
        ('transaksi_ahs', '0014_auto_20160205_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHS_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_satuan', models.FloatField()),
                ('koefisien', models.FloatField()),
                ('catatan', models.TextField(blank=True, max_length=200)),
                ('kode_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='element.Element')),
            ],
        ),
        migrations.RemoveField(
            model_name='ahs',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='ahs',
            name='harga_satuan',
        ),
        migrations.RemoveField(
            model_name='ahs',
            name='kode_element',
        ),
        migrations.RemoveField(
            model_name='ahs',
            name='koefisien',
        ),
        migrations.AddField(
            model_name='ahs_detail',
            name='nomor_ahs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi_ahs.AHS'),
        ),
    ]
