# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_ahs', '0016_auto_20160205_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahs_detail',
            options={'verbose_name': 'ahs detail', 'verbose_name_plural': 'ahs detail'},
        ),
    ]
