# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_ahs', '0019_auto_20160205_0713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ahs_detail',
            unique_together=set([('nomor_ahs', 'kode_element')]),
        ),
    ]
