# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_ahs', '0024_auto_20160205_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahs_detail',
            old_name='nomor_ahs',
            new_name='ahs',
        ),
        migrations.RenameField(
            model_name='ahs_detail',
            old_name='kode_element',
            new_name='element',
        ),
        migrations.AlterUniqueTogether(
            name='ahs_detail',
            unique_together=set([('ahs', 'element')]),
        ),
    ]
