# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_ahs', '0025_auto_20160205_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahs',
            name='total_harga',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
