# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi_ahs', '0029_auto_20160206_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahs_detail',
            name='ahs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahs_details', to='transaksi_ahs.AHS'),
        ),
    ]
