# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_proyek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyek',
            name='pengguna',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
