# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_proyek', '0002_proyek_pengguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='nomor_proyek',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
